# Generated by Django 4.2 on 2023-12-01 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_exam_model_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam_model",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 1, 11, 39, 952234)
            ),
        ),
        migrations.AlterField(
            model_name="exam_model",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 1, 11, 39, 952234)
            ),
        ),
    ]
