# Generated by Django 4.2.7 on 2023-11-21 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stu_Question",
            fields=[
                (
                    "question_db_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.question_db",
                    ),
                ),
                ("choice", models.CharField(default="E", max_length=3)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Student"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("main.question_db",),
        ),
        migrations.CreateModel(
            name="StuExam_DB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("examname", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
                ("completed", models.IntegerField(default=0)),
                (
                    "qpaper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.question_paper",
                    ),
                ),
                ("questions", models.ManyToManyField(to="student.stu_question")),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Student"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StuResults_DB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exams", models.ManyToManyField(to="student.stuexam_db")),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Student"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
